// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_restaurant/test/ui/home/restaurant_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_restaurant/data/api/api_service.dart' as _i5;
import 'package:flutter_restaurant/data/model/detail_restaurant.dart' as _i3;
import 'package:flutter_restaurant/data/model/list_restaurant.dart' as _i2;
import 'package:flutter_restaurant/data/model/search_restaurant.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListRestaurantResponse_0 extends _i1.SmartFake
    implements _i2.ListRestaurantResponse {
  _FakeListRestaurantResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailRestaurantResponse_1 extends _i1.SmartFake
    implements _i3.DetailRestaurantResponse {
  _FakeDetailRestaurantResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchRestaurantResponse_2 extends _i1.SmartFake
    implements _i4.SearchRestaurantResponse {
  _FakeSearchRestaurantResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ListRestaurantResponse> getAllRestaurants() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRestaurants,
          [],
        ),
        returnValue: _i6.Future<_i2.ListRestaurantResponse>.value(
            _FakeListRestaurantResponse_0(
          this,
          Invocation.method(
            #getAllRestaurants,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ListRestaurantResponse>);
  @override
  _i6.Future<_i3.DetailRestaurantResponse> getRestaurantById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantById,
          [id],
        ),
        returnValue: _i6.Future<_i3.DetailRestaurantResponse>.value(
            _FakeDetailRestaurantResponse_1(
          this,
          Invocation.method(
            #getRestaurantById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.DetailRestaurantResponse>);
  @override
  _i6.Future<_i4.SearchRestaurantResponse> searchRestaurant(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRestaurant,
          [query],
        ),
        returnValue: _i6.Future<_i4.SearchRestaurantResponse>.value(
            _FakeSearchRestaurantResponse_2(
          this,
          Invocation.method(
            #searchRestaurant,
            [query],
          ),
        )),
      ) as _i6.Future<_i4.SearchRestaurantResponse>);
}
